Repository depromeet/KnockKnock-Backend, pull requests merged in 2022-12, with the labels that each got.

#72 🔀 :: (#71) Relation querydsl 적용
  src/main/java/io/github/depromeet/knockknockbackend/domain/relation/domain/repository/CustomRelationRepository.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/relation/domain/repository/CustomRelationRepositoryImpl.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/relation/domain/repository/RelationRepository.java
Labels: 리팩토링

#79 🔀 :: (#62) FCM Token 가져오기
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/domain/DeviceToken.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/domain/repository/DeviceTokenRepository.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/presentation/NotificationController.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/presentation/dto/request/RegisterFcmTokenRequest.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/service/NotificationService.java
Labels: 기능 추가

#73 🔀 :: (#58) 그룹 멤버추가제거
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/domain/GroupUser.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/domain/GroupUsers.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/exception/HostCanNotLeaveGroupException.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/presentation/GroupController.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/presentation/dto/request/AddFriendToGroupRequest.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/service/GroupService.java
  src/main/java/io/github/depromeet/knockknockbackend/global/error/exception/ErrorCode.java
Labels: 기능 추가

#77 🔀 :: (#55) 오픈그룹 검색 api
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/domain/repository/GroupRepository.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/presentation/GroupController.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/service/GroupService.java
Labels: 기능 추가

#74 🔀 :: (#56) 그룹 가입 요청 수락 , 거절, 확인
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/domain/Admission.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/domain/AdmissionState.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/domain/GroupUsers.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/domain/repository/AdmissionRepository.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/exception/AdmissionNotFoundException.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/exception/AlreadyGroupEnterException.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/facade/AdmissionFacade.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/presentation/GroupController.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/presentation/dto/response/AdmissionInfoDto.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/presentation/dto/response/AdmissionInfoListResponse.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/service/AdmissionService.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/service/GroupService.java
  src/main/java/io/github/depromeet/knockknockbackend/global/error/exception/ErrorCode.java
Labels: 기능 추가

#86 🔀 :: (#85) Build Actions 생성
  .github/workflows/build.yml
  Dockerfile
Labels: 프로젝트 설정

#84 🔀 :: (#83) Relation Service improve
  src/main/java/io/github/depromeet/knockknockbackend/domain/relation/domain/repository/CustomRelationRepository.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/relation/domain/repository/CustomRelationRepositoryImpl.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/relation/service/RelationService.java
Labels: 리팩토링

#91 🔀 :: Notification에 Group 연관관계 추가
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/domain/Notification.java
Labels: 기능 추가

#95 🔀 :: (#80) FCM 즉시 알림 전송 구현
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/domain/Group.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/domain/DeviceToken.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/domain/NightCondition.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/domain/Notification.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/domain/repository/DeviceTokenRepository.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/exception/FcmResponseException.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/presentation/NotificationController.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/presentation/dto/request/SendInstanceRequest.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/service/NotificationService.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/user/domain/User.java
  src/main/java/io/github/depromeet/knockknockbackend/global/error/exception/ErrorCode.java
Labels: 기능 추가

#102 🔀 :: (#101) 추천메세지 조회 API
  src/main/java/io/github/depromeet/knockknockbackend/domain/recommendmessage/domain/RecommendMessage.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/recommendmessage/domain/RecommendMessageContent.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/recommendmessage/domain/repository/RecommendMessageRepository.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/recommendmessage/presentation/RecommendMessageController.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/recommendmessage/presentation/dto/response/QueryRecommendMessageResponse.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/recommendmessage/presentation/dto/response/QueryRecommendMessageResponseElement.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/recommendmessage/service/RecommendMessageService.java
Labels: 기능 추가

#108 🔀 :: (#107) 추천메세지 속성 변경 후 쿼리 메서드 미변경 버그 수정
  src/main/java/io/github/depromeet/knockknockbackend/domain/recommendmessage/domain/repository/RecommendMessageRepository.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/recommendmessage/service/RecommendMessageService.java
Labels: 버그

#104 🔀 :: (#103) 리액션 등록/수정/삭제 API
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/domain/Notification.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/reaction/domain/NotificationReaction.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/reaction/domain/Reaction.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/reaction/domain/repository/NotificationReactionRepository.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/reaction/exception/ReactionForbiddenException.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/reaction/presentation/ReactionController.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/reaction/presentation/dto/request/RegisterReactionRequest.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/reaction/service/ReactionService.java
  src/main/java/io/github/depromeet/knockknockbackend/global/database/BaseTimeEntity.java
  src/main/java/io/github/depromeet/knockknockbackend/global/error/exception/ErrorCode.java
Labels: 기능 추가

#92 🔀 :: (#76) 그룹 조회 페이지네이션
  src/main/generated/io/github/depromeet/knockknockbackend/domain/group/domain/QGroup.java
  src/main/generated/io/github/depromeet/knockknockbackend/domain/group/domain/QGroupUser.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/domain/Group.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/domain/repository/CustomGroupRepository.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/domain/repository/CustomGroupRepositoryImpl.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/domain/repository/CustomGroupUserRepository.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/domain/repository/CustomGroupUserRepositoryImpl.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/domain/repository/GroupRepository.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/domain/repository/GroupUserRepository.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/presentation/GroupController.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/presentation/dto/response/GroupBriefInfoListResponse.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/service/GroupService.java
Labels: 기능 추가, 리팩토링

#94 🔀 :: (#57) 그룹초대 코드 발급,검증
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/domain/GroupUsers.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/domain/InviteTokenRedisEntity.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/domain/repository/InviteTokenRedisEntityRepository.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/exception/InvalidInviteTokenException.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/exception/NotMemberException.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/presentation/GroupController.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/presentation/dto/response/GroupInviteLinkResponse.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/service/GroupService.java
  src/main/java/io/github/depromeet/knockknockbackend/global/error/exception/ErrorCode.java
  src/main/java/io/github/depromeet/knockknockbackend/global/utils/generate/TokenGenerator.java
Labels: 기능 추가

#121 🔀 :: (#120) 스웨거 Api 설명달기 - users, relations, options
  src/main/java/io/github/depromeet/knockknockbackend/domain/option/presentation/OptionController.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/relation/presentation/RelationController.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/user/presentation/UserController.java
Labels: DOCS

#113 🔀 :: (#89) 가입요청 수락
  src/main/java/io/github/depromeet/knockknockbackend/domain/admission/domain/Admission.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/admission/domain/AdmissionState.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/admission/domain/repository/AdmissionRepository.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/admission/exception/AdmissionNotFoundException.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/admission/service/AdmissionService.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/domain/GroupUser.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/domain/GroupUsers.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/domain/repository/CustomGroupUserRepositoryImpl.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/domain/repository/GroupUserRepository.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/domain/usecase/AdmissionUsecase.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/facade/AdmissionFacade.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/presentation/GroupController.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/presentation/dto/response/AdmissionInfoDto.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/service/GroupService.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/service/GroupUtils.java
Labels: 기능 추가, 리팩토링

#116 🔀 :: (#99) 친구 방 자동 제목 추가
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/domain/Group.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/domain/GroupUsers.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/service/GroupService.java
Labels: 기능 추가, 리팩토링

#118 🔀 :: (#109) 프로필 업데이트
  src/main/java/io/github/depromeet/knockknockbackend/domain/user/domain/User.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/user/domain/vo/UserInfoVO.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/user/presentation/UserController.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/user/presentation/dto/request/ChangeProfileRequest.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/user/presentation/dto/response/UserProfileResponse.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/user/service/UserService.java
Labels: 기능 추가

#126 🔀 :: (#125) 그룹 도메인 리팩터링
  src/main/java/io/github/depromeet/knockknockbackend/domain/admission/service/AdmissionService.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/domain/Group.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/domain/GroupUser.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/domain/GroupUsers.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/domain/vo/GroupBaseInfoVo.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/presentation/GroupController.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/presentation/dto/response/CreateGroupResponse.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/service/BackgroundImageService.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/service/GroupService.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/service/GroupUtils.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/service/ThumbnailImageService.java
Labels: 리팩토링

#132 🔀 :: (#97) 떠오르는 카테고리 조회
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/domain/repository/CategoryRepository.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/presentation/GroupController.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/service/CategoryService.java
Labels: 기능 추가

#131 🔀 :: (#93) 떠오르는 그룹 조회
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/domain/repository/GroupRepository.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/presentation/GroupController.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/presentation/dto/response/GroupBriefInfos.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/service/GroupService.java
Labels: 기능 추가

#135 🔀 :: (#134) actuator 설정
  build.gradle
  src/main/java/io/github/depromeet/knockknockbackend/global/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: 기능 추가

#129 🔀 :: (#123) 보관함 저장, 삭제 API
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/domain/repository/CustomGroupUserRepository.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/domain/repository/CustomGroupUserRepositoryImpl.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/domain/repository/NotificationRepository.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/exception/NotificationForbiddenException.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/exception/NotificationNotFoundException.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/storage/domain/Storage.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/storage/domain/repository/StorageRepository.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/storage/exception/StorageForbiddenException.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/storage/exception/StorageNotFoundException.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/storage/presentation/StorageController.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/storage/service/StorageService.java
  src/main/java/io/github/depromeet/knockknockbackend/global/error/exception/ErrorCode.java
Labels: 기능 추가

#139 🔀 :: (#138) 리액션 수정 API 리팩토링
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/domain/repository/NotificationRepository.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/reaction/exception/ReactionAlreadyExistException.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/reaction/presentation/ReactionController.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/reaction/presentation/dto/request/RegisterReactionRequest.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/reaction/service/ReactionService.java
  src/main/java/io/github/depromeet/knockknockbackend/global/error/exception/ErrorCode.java
Labels: 리팩토링, 버그

#137 🔀 :: (#128) 보관함 리스트 조회 API
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/domain/repository/CustomNotificationRepository.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/domain/repository/CustomNotificationRepositoryImpl.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/domain/repository/NotificationRepository.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/domain/vo/NotificationReactionCountInfoVo.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/presentation/dto/response/NotificationReactionResponseElement.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/presentation/dto/response/QueryNotificationListInStorageResponse.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/service/NotificationService.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/reaction/domain/repository/NotificationReactionRepository.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/storage/presentation/StorageController.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/storage/service/StorageService.java
Labels: 기능 추가

#150 🔀 :: (#78) 스웨거 customize , 앱 버젼체크
  src/main/java/io/github/depromeet/knockknockbackend/domain/asset/domain/AppVersion.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/asset/domain/repository/AppVersionRepository.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/asset/exception/AppVersionNotFoundException.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/asset/presentation/AssetController.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/asset/presentation/dto/response/AppVersionResponse.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/asset/service/AssetService.java
  src/main/java/io/github/depromeet/knockknockbackend/global/annotation/DisableSecurity.java
  src/main/java/io/github/depromeet/knockknockbackend/global/config/SecurityConfig.java
  src/main/java/io/github/depromeet/knockknockbackend/global/config/SwaggerConfig.java
  src/main/java/io/github/depromeet/knockknockbackend/global/error/exception/ErrorCode.java
  src/main/resources/data.sql
Labels: 기능 추가, 리팩토링

#141 🔀 :: (#61) 이미지 등록 Api
  build.gradle
  src/main/java/io/github/depromeet/knockknockbackend/domain/image/exception/BadFileExtensionException.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/image/exception/FileEmptyException.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/image/exception/FileUploadFailException.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/image/presentation/ImageController.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/image/presentation/dto/response/UploadImageResponse.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/image/service/ImageService.java
  src/main/java/io/github/depromeet/knockknockbackend/global/error/exception/ErrorCode.java
Labels: 기능 추가

#136 🔀 :: (#133) 떠오르는 그룹,카테고리 조회 캐싱
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/presentation/dto/response/CategoryDto.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/presentation/dto/response/CategoryListResponse.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/presentation/dto/response/GroupBriefInfoDto.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/presentation/dto/response/GroupBriefInfos.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/service/CategoryService.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/service/GroupService.java
  src/main/java/io/github/depromeet/knockknockbackend/global/config/RedisCacheConfig.java
Labels: 기능 추가

#145 🔀 :: (#144) global 밸리데이션 에러 핸들링
  src/main/java/io/github/depromeet/knockknockbackend/global/error/ErrorResponse.java
  src/main/java/io/github/depromeet/knockknockbackend/global/error/ExceptionFilter.java
  src/main/java/io/github/depromeet/knockknockbackend/global/error/GlobalExceptionHandler.java
  src/main/java/io/github/depromeet/knockknockbackend/global/error/exception/ErrorCode.java
Labels: 기능 추가

#146 🔀 :: (#20) global 성공응답 핸들링
  src/main/java/io/github/depromeet/knockknockbackend/global/successResponse/SuccessResponse.java
  src/main/java/io/github/depromeet/knockknockbackend/global/successResponse/SuccessResponseAdvice.java
Labels: 기능 추가

#151 🔀 :: (#117) 그룹 컨트롤러 스웨거, 밸리데이션 보강
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/presentation/GroupController.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/presentation/dto/request/AddFriendToGroupRequest.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/presentation/dto/request/CreateOpenGroupRequest.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/presentation/dto/request/UpdateGroupRequest.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/service/GroupService.java
  src/main/java/io/github/depromeet/knockknockbackend/global/config/SwaggerConfig.java
Labels: 리팩토링

#147 🔀 :: (#140) 푸쉬알림 목록 조회시 자신의 리액션 정보에 속성 추가
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/domain/vo/NotificationReactionInfoVo.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/presentation/dto/response/MyNotificationReactionResponseElement.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/presentation/dto/response/QueryNotificationListResponseElement.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/presentation/dto/response/QueryNotificationReactionResponseElement.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/service/NotificationService.java
Labels: 기능 추가

#154 🔀 :: (#100) 푸쉬알림 받은 유저 엔티티 생성
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/domain/Notification.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/domain/NotificationReceiver.java
Labels: 기능 추가

#153 🔀 :: (#152) GlobalExceptionFilter Bug
  src/main/java/io/github/depromeet/knockknockbackend/global/error/ExceptionFilter.java
Labels: 버그

#157 🔀 :: (#156) Aws S3 환경설정
  src/main/java/io/github/depromeet/knockknockbackend/domain/image/service/ImageService.java
  src/main/java/io/github/depromeet/knockknockbackend/global/config/S3Config.java
  src/main/resources/application.yml
Labels: 기능 추가, 프로젝트 설정

#162 🔀 :: (#161) BlockUser 엔티티 생성
  src/main/java/io/github/depromeet/knockknockbackend/domain/relation/domain/BlockUser.java
Labels: 기능 추가

#163 🔀 :: (#148) 알림 송신시 차단 유저에게 알람 미전송
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/domain/Notification.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/domain/NotificationReceiver.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/domain/repository/CustomNotificationRepository.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/domain/repository/CustomNotificationRepositoryImpl.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/service/NotificationService.java
Labels: 기능 추가

#159 🔀 :: (#142) Api 버저닝
  src/main/java/io/github/depromeet/knockknockbackend/domain/asset/presentation/AssetController.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/credential/presentation/CredentialController.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/presentation/GroupController.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/image/presentation/ImageController.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/presentation/NotificationController.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/option/presentation/OptionController.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/reaction/presentation/ReactionController.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/recommendmessage/presentation/RecommendMessageController.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/relation/presentation/RelationController.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/storage/presentation/StorageController.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/user/presentation/UserController.java
  src/main/java/io/github/depromeet/knockknockbackend/global/config/SecurityConfig.java
Labels: 기능 추가

#164 🔀 :: (#124) Notification 삭제 기능을 위한 deleted 속성 추가
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/domain/Notification.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/domain/repository/NotificationRepository.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/service/NotificationService.java
Labels: 기능 추가

#167 🔀 :: (#165) 푸쉬알림 삭제 구현
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/domain/Notification.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/presentation/NotificationController.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/service/NotificationService.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/reaction/presentation/ReactionController.java
Labels: 기능 추가

#170 🔀 :: (#169) ResponseBodyAdvice 적용 범위 미설정으로 인한 스웨거 안보이는 문제
  src/main/java/io/github/depromeet/knockknockbackend/global/successResponse/SuccessResponseAdvice.java
Labels: 버그

#173 🔀 :: (#172) 스웨거 ssl 설정시 요청 패스 문제 해결
  src/main/java/io/github/depromeet/knockknockbackend/global/config/SwaggerConfig.java
Labels: 버그

#179 🔀 :: (#175) 유저서비스 트랜잭션 어노테이션 추가
  src/main/java/io/github/depromeet/knockknockbackend/domain/user/service/UserService.java
Labels: 버그

#181 🚀 :: v0.0.6-1
  src/main/java/io/github/depromeet/knockknockbackend/domain/user/service/UserService.java
Labels: 기능 추가

#176 🔀 :: (#168) 최신 푸쉬알림 조회
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/domain/repository/CustomNotificationRepository.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/domain/repository/CustomNotificationRepositoryImpl.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/presentation/NotificationController.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/presentation/dto/response/QueryNotificationListLatestResponse.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/service/NotificationService.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/reaction/domain/repository/NotificationReactionRepository.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/reaction/presentation/ReactionController.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/storage/service/StorageService.java
Labels: 기능 추가

#182 🔀 :: (#177) 똑똑 미리 체험하기
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/domain/NotificationExperience.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/domain/repository/NotificationExperienceRepository.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/presentation/NotificationController.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/presentation/dto/request/SendInstanceToMeBeforeSignUpRequest.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/service/NotificationService.java
Labels: 기능 추가

#186 🔀 :: (#184) 예약 알림 엔티티 생성
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/domain/Reservation.java
Labels: 기능 추가

#185 🔀 :: (#183) 액츄에이터 스프링 시큐리티 버져닝 제거
  src/main/java/io/github/depromeet/knockknockbackend/global/config/SecurityConfig.java
Labels: 버그

#193 🔀 :: (#187) 알림방 목록에 예약알림 내용 표시
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/domain/Reservation.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/domain/repository/ReservationRepository.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/presentation/dto/response/QueryNotificationListResponse.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/presentation/dto/response/QueryReservationListResponseElement.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/service/NotificationService.java
Labels: 기능 추가

#196 🔀 :: (#192) Notification엔티티에서 sendAt 속성 삭제
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/domain/repository/CustomGroupRepositoryImpl.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/domain/repository/CustomGroupUserRepositoryImpl.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/presentation/dto/response/GroupBriefInfoDto.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/domain/Notification.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/domain/NotificationExperience.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/presentation/NotificationController.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/presentation/dto/response/QueryNotificationListResponse.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/presentation/dto/response/QueryNotificationListResponseElement.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/service/NotificationService.java
Labels: 리팩토링

#198 🔀 :: (#197) oauth ocid 방식으로 회원가입
  src/main/java/io/github/depromeet/knockknockbackend/domain/credential/presentation/CredentialController.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/credential/presentation/dto/request/RegisterRequest.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/credential/presentation/dto/response/AvailableRegisterResponse.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/credential/service/CredentialService.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/credential/service/GoogleOauthStrategy.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/credential/service/KakaoOauthStrategy.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/credential/service/OIDCDecodePayload.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/credential/service/OauthOIDCProvider.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/credential/service/OauthProvider.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/credential/service/OauthStrategy.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/user/domain/User.java
  src/main/java/io/github/depromeet/knockknockbackend/global/config/RedisCacheConfig.java
  src/main/java/io/github/depromeet/knockknockbackend/global/security/JwtOIDCProvider.java
  src/main/java/io/github/depromeet/knockknockbackend/global/utils/api/client/GoogleAuthClient.java
  src/main/java/io/github/depromeet/knockknockbackend/global/utils/api/client/KakaoOauthClient.java
  src/main/java/io/github/depromeet/knockknockbackend/global/utils/api/dto/response/OIDCPublicKeyDto.java
  src/main/java/io/github/depromeet/knockknockbackend/global/utils/api/dto/response/OIDCPublicKeysResponse.java
Labels: 기능 추가, 리팩토링

#203 🔀 :: (#194) 푸쉬알림 예약 생성/수정/삭제
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/domain/Reservation.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/exception/ReservationForbiddenException.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/exception/ReservationNotFoundException.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/presentation/NotificationController.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/presentation/dto/request/ChangeSendAtReservationRequest.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/presentation/dto/request/SendReservationRequest.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/service/NotificationService.java
  src/main/java/io/github/depromeet/knockknockbackend/global/error/exception/ErrorCode.java
Labels: 기능 추가

#207 🔀 :: (#206) 보관함 삭제시 여러 개의 푸쉬알림 삭제
  src/main/java/io/github/depromeet/knockknockbackend/domain/storage/domain/repository/StorageRepository.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/storage/presentation/StorageController.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/storage/presentation/dto/request/DeleteStorage.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/storage/service/StorageService.java
Labels: 기능 추가

#209 🔀 :: (#188) 유저 탈퇴
  src/main/java/io/github/depromeet/knockknockbackend/domain/credential/event/DeleteUserEvent.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/credential/presentation/CredentialController.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/credential/service/CredentialService.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/credential/service/GoogleOauthStrategy.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/credential/service/KakaoOauthStrategy.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/credential/service/OauthStrategy.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/user/domain/AccountState.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/user/domain/User.java
  src/main/java/io/github/depromeet/knockknockbackend/global/config/SecurityConfig.java
  src/main/java/io/github/depromeet/knockknockbackend/global/event/DeleteUserEventHandler.java
  src/main/java/io/github/depromeet/knockknockbackend/global/utils/api/client/GoogleUnlinkClient.java
  src/main/java/io/github/depromeet/knockknockbackend/global/utils/api/client/KakaoInfoClient.java
Labels: 기능 추가

#210 🔀 :: (#190) 유저 로그인전 유저 상태확인
  src/main/java/io/github/depromeet/knockknockbackend/domain/credential/exception/ForbiddenUserException.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/credential/service/CredentialService.java
  src/main/java/io/github/depromeet/knockknockbackend/global/error/exception/ErrorCode.java
  src/main/java/io/github/depromeet/knockknockbackend/global/utils/user/UserUtilsImpl.java
Labels: 기능 추가, 리팩토링

#213 🔀 :: (#212) 앱 아이디 로 aud 인증
  src/main/java/io/github/depromeet/knockknockbackend/domain/credential/service/GoogleOauthStrategy.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/credential/service/KakaoOauthStrategy.java
  src/main/java/io/github/depromeet/knockknockbackend/global/property/OauthProperties.java
  src/main/resources/application.yml
Labels: 버그

#211 🔀 :: (#191) 유저 권한 인가
  src/main/java/io/github/depromeet/knockknockbackend/domain/credential/service/CredentialService.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/user/domain/AccountRole.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/user/domain/User.java
  src/main/java/io/github/depromeet/knockknockbackend/global/config/SecurityConfig.java
  src/main/java/io/github/depromeet/knockknockbackend/global/security/JwtTokenFilter.java
  src/main/java/io/github/depromeet/knockknockbackend/global/security/JwtTokenProvider.java
  src/main/java/io/github/depromeet/knockknockbackend/global/security/auth/AuthDetailsService.java
Labels: 기능 추가

#217 🔀 :: (#81)(#82) 친구 수락&거절 Api
  src/main/java/io/github/depromeet/knockknockbackend/domain/relation/exception/AlreadyFriendException.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/relation/exception/FriendRequestNotFoundException.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/relation/presentation/RelationController.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/relation/presentation/dto/request/FriendRequest.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/relation/service/RelationService.java
  src/main/java/io/github/depromeet/knockknockbackend/global/error/exception/ErrorCode.java
Labels: 기능 추가

#220 🔀 :: (#180) 슬랙 에러 알림
  build.gradle
  src/main/java/io/github/depromeet/knockknockbackend/global/config/CacheBodyFilter.java
  src/main/java/io/github/depromeet/knockknockbackend/global/error/GlobalExceptionHandler.java
  src/main/java/io/github/depromeet/knockknockbackend/global/slack/SlackProvider.java
  src/main/java/io/github/depromeet/knockknockbackend/infrastructor/slack/SlackConfig.java
  src/main/resources/application.yml
Labels: 기능 추가

#222 🚀 :: v0.1.1
  build.gradle
  src/main/java/io/github/depromeet/knockknockbackend/domain/relation/exception/AlreadyFriendException.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/relation/exception/FriendRequestNotFoundException.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/relation/presentation/RelationController.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/relation/presentation/dto/request/FriendRequest.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/relation/service/RelationService.java
  src/main/java/io/github/depromeet/knockknockbackend/global/config/CacheBodyFilter.java
  src/main/java/io/github/depromeet/knockknockbackend/global/error/GlobalExceptionHandler.java
  src/main/java/io/github/depromeet/knockknockbackend/global/error/exception/ErrorCode.java
  src/main/java/io/github/depromeet/knockknockbackend/global/slack/SlackProvider.java
  src/main/java/io/github/depromeet/knockknockbackend/infrastructor/slack/SlackConfig.java
  src/main/resources/application.yml
Labels: 기능 추가

#219 🔀 :: (#218) Alarm 서비스
  src/main/java/io/github/depromeet/knockknockbackend/domain/alarm/domain/Alarm.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/alarm/domain/repository/AlarmRepository.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/alarm/domain/types/AlarmType.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/alarm/presentation/AlarmController.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/alarm/presentation/dto/response/QueryAlarmCountResponse.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/alarm/presentation/dto/response/QueryAlarmListResponse.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/alarm/presentation/dto/response/QueryAlarmListResponseElement.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/alarm/service/AlarmService.java
Labels: 기능 추가

#224 🔀 :: (#223) 슬랙 에러 알림 getRequest null 문제 해결
  src/main/java/io/github/depromeet/knockknockbackend/global/error/GlobalExceptionHandler.java
  src/main/java/io/github/depromeet/knockknockbackend/global/slack/SlackProvider.java
Labels: 버그

#231 🔀 :: (#189) 신고하기 기능
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/service/NotificationService.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/service/NotificationUtils.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/report/domain/Report.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/report/domain/ReportReason.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/report/domain/repository/ReportRepository.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/report/event/NewReportEvent.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/report/exception/CannotReportMeException.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/report/exception/ReportNotFoundException.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/report/presentation/ReportController.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/report/presentation/dto/request/ReportNotificationRequest.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/report/presentation/dto/response/ReportNotificationResponse.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/report/service/ReportService.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/report/service/ReportUtils.java
  src/main/java/io/github/depromeet/knockknockbackend/global/error/exception/ErrorCode.java
  src/main/java/io/github/depromeet/knockknockbackend/global/slack/SlackEventHandler.java
Labels: 기능 추가

#228 🔀 :: (#226) 로그아웃 기능추가
  src/main/java/io/github/depromeet/knockknockbackend/domain/credential/event/LogoutUserEvent.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/credential/presentation/CredentialController.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/credential/service/CredentialService.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/user/domain/User.java
  src/main/java/io/github/depromeet/knockknockbackend/global/config/SecurityConfig.java
Labels: 기능 추가

#230 🔀 :: (#229) 서블릿,스프링 기본 에러 핸들링
  src/main/java/io/github/depromeet/knockknockbackend/global/error/GlobalExceptionHandler.java
Labels: 리팩토링

#233 🔀 :: (#221) 회원가입 슬랙알림
  src/main/java/io/github/depromeet/knockknockbackend/domain/credential/service/CredentialService.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/user/domain/User.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/user/event/RegisterUserEvent.java
  src/main/java/io/github/depromeet/knockknockbackend/global/slack/SlackEventHandler.java
Labels: 기능 추가

#235 🔀 :: (#234) fcm 인증방식 환경변수로. 똑똑미리체험하기 회원가입전 가능하도록 수정
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/presentation/NotificationController.java
  src/main/java/io/github/depromeet/knockknockbackend/global/config/SecurityConfig.java
  src/main/java/io/github/depromeet/knockknockbackend/infrastructor/fcm/FcmConfig.java
Labels: 리팩토링

#241 🔀 :: (#238) 이미지 최대크기 키우기
  src/main/resources/application.yml
Labels: 프로젝트 설정

#240 🔀 :: (#239) 설정 값 가져오는 Api
  src/main/java/io/github/depromeet/knockknockbackend/domain/option/presentation/OptionController.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/option/presentation/dto/response/QueryOptionsResponse.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/option/service/OptionService.java
Labels: 기능 추가

#242 🔀 :: (#237) 회원가입 시 옵션 생성
  src/main/java/io/github/depromeet/knockknockbackend/domain/credential/service/CredentialService.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/credential/service/UserOptionService.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/option/domain/Option.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/option/service/OptionService.java
Labels: 기능 추가

#227 🔀 :: (#195) 예약 알림 전송
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/domain/Notification.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/domain/repository/CustomNotificationRepositoryImpl.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/domain/repository/ReservationRepository.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/presentation/NotificationController.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/service/NotificationReservationScheduler.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/service/NotificationService.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/service/ReservationService.java
  src/main/java/io/github/depromeet/knockknockbackend/global/config/ScheduledConfig.java
  src/main/java/io/github/depromeet/knockknockbackend/infrastructor/fcm/FcmService.java
Labels: 기능 추가

#245 🔀 :: (#244) 보관함 알림방 조회 조건 수정
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/domain/repository/CustomNotificationRepository.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/domain/repository/CustomNotificationRepositoryImpl.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/storage/presentation/StorageController.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/storage/presentation/dto/request/QueryStorageByGroupIds.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/storage/service/StorageService.java
Labels: 리팩토링

#251 🔀 :: (#208) 로그아웃/회원탈퇴 시FCM 토큰 삭제
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/domain/repository/DeviceTokenRepository.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/event/DeviceTokenEvent.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/user/domain/User.java
  src/main/java/io/github/depromeet/knockknockbackend/global/event/DeviceTokenServiceEventHandler.java
Labels: 기능 추가

#254 🔀 :: (#253) 옵션 엔티티 noarg 생성자 문제 해결
  src/main/java/io/github/depromeet/knockknockbackend/domain/credential/service/CredentialService.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/option/domain/Option.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/option/domain/repository/OptionRepository.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/option/service/OptionService.java
Labels: 리팩토링, 버그

#258 🔀 :: 푸쉬알림 대상자 없을 때 에러 발생부분 수정
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/service/NotificationService.java
Labels: 버그

#262 🔀 :: (#261) 리프레쉬 토큰 만료시 403 에러 반환
  src/main/java/io/github/depromeet/knockknockbackend/domain/credential/exception/RefreshTokenExpiredException.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/credential/service/CredentialService.java
  src/main/java/io/github/depromeet/knockknockbackend/global/error/exception/ErrorCode.java
  src/main/java/io/github/depromeet/knockknockbackend/global/security/JwtTokenProvider.java
Labels: 리팩토링, 버그

#260 🔀 :: (#249) 예약 알림 한 사람당 1개만 생성 가능
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/domain/repository/GroupUserRepository.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/domain/Reservation.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/domain/repository/ReservationRepository.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/exception/ReservationAlreadyExistException.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/presentation/dto/response/QueryNotificationListResponse.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/service/NotificationService.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/service/ReservationService.java
  src/main/java/io/github/depromeet/knockknockbackend/global/error/exception/ErrorCode.java
Labels: 리팩토링

#266 🔀 :: (#265) 친구 삭제 Api
  src/main/java/io/github/depromeet/knockknockbackend/domain/relation/domain/repository/CustomRelationRepository.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/relation/domain/repository/CustomRelationRepositoryImpl.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/relation/exception/NotFriendRelationException.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/relation/presentation/RelationController.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/relation/service/RelationService.java
  src/main/java/io/github/depromeet/knockknockbackend/global/error/exception/ErrorCode.java
Labels: 기능 추가
