Repository depromeet/KnockKnock-Backend, pull requests merged in 2022-11, with the labels that each got.

#11 카카오 토큰 유효성 체크 , 디비 저장
  build.gradle
  src/main/java/io/github/depromeet/knockknockbackend/domain/credential/exception/AlreadySignUpUserException.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/credential/exception/OauthTokenInvalidException.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/credential/presentation/CredentialController.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/credential/presentation/dto/request/OauthCodeRequest.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/credential/presentation/dto/response/OauthLoginLinkResponse.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/credential/presentation/dto/response/TokenResponse.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/credential/presentation/dto/response/UserProfileDto.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/credential/service/CredentialService.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/credential/service/KakaoOauthStrategy.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/credential/service/OauthCommonUserInfoDto.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/credential/service/OauthFactory.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/credential/service/OauthProvider.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/credential/service/OauthStrategy.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/user/domain/User.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/user/domain/repository/UserRepository.java
  src/main/java/io/github/depromeet/knockknockbackend/global/config/ConfigurationPropertiesConfig.java
  src/main/java/io/github/depromeet/knockknockbackend/global/config/SecurityConfig.java
  src/main/java/io/github/depromeet/knockknockbackend/global/error/exception/ErrorCode.java
  src/main/java/io/github/depromeet/knockknockbackend/global/property/OauthProperties.java
  src/main/java/io/github/depromeet/knockknockbackend/global/security/JwtTokenFilter.java
  src/main/java/io/github/depromeet/knockknockbackend/global/utils/api/FeignClientErrorDecoder.java
  src/main/java/io/github/depromeet/knockknockbackend/global/utils/api/FeignConfiguration.java
  src/main/java/io/github/depromeet/knockknockbackend/global/utils/api/client/KakaoInfoClient.java
  src/main/java/io/github/depromeet/knockknockbackend/global/utils/api/client/KakaoOauthClient.java
  src/main/java/io/github/depromeet/knockknockbackend/global/utils/api/dto/response/KakaoAccessTokenInfoResponse.java
  src/main/java/io/github/depromeet/knockknockbackend/global/utils/api/dto/response/KakaoInformationResponse.java
  src/main/java/io/github/depromeet/knockknockbackend/global/utils/api/dto/response/OauthAccessTokenResponse.java
  src/main/java/io/github/depromeet/knockknockbackend/global/utils/api/exception/OtherServerBadRequestException.java
  src/main/java/io/github/depromeet/knockknockbackend/global/utils/api/exception/OtherServerExpiredTokenException.java
  src/main/java/io/github/depromeet/knockknockbackend/global/utils/api/exception/OtherServerForbiddenException.java
  src/main/java/io/github/depromeet/knockknockbackend/global/utils/api/exception/OtherServerUnauthorizedException.java
  src/main/resources/application.yml
  src/test/java/io/github/depromeet/knockknockbackend/domain/credential/service/KakaoAuthServiceTest.java
Labels: 기능 추가, 리팩토링

#13 레디스 설정
  docker-compose.yml
  src/main/java/io/github/depromeet/knockknockbackend/infrastructor/redis/RedisConfig.java
  src/main/java/io/github/depromeet/knockknockbackend/infrastructor/redis/RedisService.java
  src/main/java/io/github/depromeet/knockknockbackend/infrastructor/redis/RedisServiceImpl.java
Labels: 기능 추가, 프로젝트 설정

#15 🔀 :: (#14) Redis 설정 효율화
  src/main/java/io/github/depromeet/knockknockbackend/domain/example/domain/RedisEntityExample.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/example/domain/repository/ExampleRedisEntityRepository.java
  src/main/java/io/github/depromeet/knockknockbackend/infrastructor/redis/RedisConfig.java
  src/main/java/io/github/depromeet/knockknockbackend/infrastructor/redis/RedisService.java
  src/main/java/io/github/depromeet/knockknockbackend/infrastructor/redis/RedisServiceImpl.java
Labels: 리팩토링

#21 🔀 :: (#8) 구글 oauth 로그인 기능 추가
  src/main/java/io/github/depromeet/knockknockbackend/global/error/GlobalExceptionHandler.java
Labels: 기능 추가

#16 🔀 :: (#12) jwtTokenProvider 어세스,리프레쉬 토큰 관련 로직 추가
  src/main/java/io/github/depromeet/knockknockbackend/global/security/JwtTokenProvider.java
Labels: 기능 추가

#19 🔀 :: (#6) 스웨거 추가
  build.gradle
  src/main/java/io/github/depromeet/knockknockbackend/global/config/SecurityConfig.java
  src/main/java/io/github/depromeet/knockknockbackend/global/config/SwaggerConfig.java
  src/main/resources/application.yml
Labels: 기능 추가

#23 🔀 :: (#22) 유저 닉네임으로 검색 Api
  src/main/java/io/github/depromeet/knockknockbackend/domain/user/domain/User.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/user/domain/repository/UserRepository.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/user/presentation/UserController.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/user/presentation/dto/response/QueryUserByNicknameResponse.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/user/presentation/dto/response/QueryUserByNicknameResponseElement.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/user/service/UserService.java
Labels: 기능 추가

#18 🔀 :: (#9) 구글 oauth 로그인 기능 추가
  build.gradle
  src/main/java/io/github/depromeet/knockknockbackend/domain/credential/presentation/CredentialController.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/credential/service/CredentialService.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/credential/service/GoogleOauthStrategy.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/user/domain/User.java
  src/main/java/io/github/depromeet/knockknockbackend/global/utils/api/FeignClientErrorDecoder.java
  src/main/java/io/github/depromeet/knockknockbackend/global/utils/api/FeignConfiguration.java
  src/main/java/io/github/depromeet/knockknockbackend/global/utils/api/client/GoogleAuthClient.java
  src/main/java/io/github/depromeet/knockknockbackend/global/utils/api/client/GoogleInfoClient.java
  src/main/java/io/github/depromeet/knockknockbackend/global/utils/api/client/KakaoOauthClient.java
  src/main/java/io/github/depromeet/knockknockbackend/global/utils/api/dto/response/GoogleInformationResponse.java
  src/main/resources/application.yml
Labels: 기능 추가

#25 🔀 :: (#24) 새로운 푸시알림 설정
  src/main/java/io/github/depromeet/knockknockbackend/domain/option/domain/Option.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/option/domain/repository/OptionRepository.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/option/exception/OptionNotFoundException.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/option/presentation/OptionController.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/option/service/OptionService.java
  src/main/java/io/github/depromeet/knockknockbackend/global/error/exception/ErrorCode.java
  src/main/java/io/github/depromeet/knockknockbackend/global/utils/security/SecurityUtils.java
Labels: 기능 추가

#29 🔀 :: (#28) 리액션 알림 Api
  src/main/java/io/github/depromeet/knockknockbackend/domain/option/presentation/OptionController.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/option/service/OptionService.java
Labels: 기능 추가

#31 🔀 :: (#30) 야간 푸시알림 Api
  src/main/java/io/github/depromeet/knockknockbackend/domain/option/presentation/OptionController.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/option/service/OptionService.java
Labels: 기능 추가

#35 🔀 :: (#17) 소셜로그인 후 토큰발급 , 토큰 리프레쉬
  src/main/java/io/github/depromeet/knockknockbackend/domain/credential/domain/RefreshTokenRedisEntity.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/credential/domain/repository/RefreshTokenRedisEntityRepository.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/credential/presentation/CredentialController.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/credential/presentation/dto/request/TokenRefreshRequest.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/credential/presentation/dto/response/AfterOauthResponse.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/credential/presentation/dto/response/AuthTokensResponse.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/credential/presentation/dto/response/UserProfileDto.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/credential/service/CredentialService.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/credential/service/GoogleOauthStrategy.java
  src/main/java/io/github/depromeet/knockknockbackend/global/security/JwtTokenProvider.java
  src/main/java/io/github/depromeet/knockknockbackend/global/security/auth/AuthDetailsService.java
  src/main/java/io/github/depromeet/knockknockbackend/global/utils/api/client/GoogleAuthClient.java
Labels: 기능 추가

#42 🔀 :: (#41) 스웨거 요청 예시 카멜 케이스 적용
  src/main/java/io/github/depromeet/knockknockbackend/global/config/SwaggerConfig.java
Labels: 기능 추가

#46 🔀 :: (#44) application.yml 개선
  src/main/resources/application.yml
Labels: 프로젝트 설정

#52 🔀 :: (#37) 친구들과 방 만들기
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/domain/BackgroundImage.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/domain/Category.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/domain/Group.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/domain/GroupUser.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/domain/GroupUsers.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/domain/Thumbnail.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/domain/repository/BackGroundImageRepository.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/domain/repository/MemberRepository.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/domain/repository/ThumbnailRepository.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/domain/vo/GroupBaseInfoVo.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/exception/BackgroundImageNotFoundException.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/exception/ThumbNailImageNotFoundException.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/presentation/GroupController.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/presentation/dto/request/CreateFriendGroupRequest.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/presentation/dto/request/CreateOpenGroupRequest.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/presentation/dto/response/CreateGroupResponse.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/service/BackgroundImageService.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/service/GroupService.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/service/ThumbnailImageService.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/user/UserUtils.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/user/service/UserService.java
  src/main/java/io/github/depromeet/knockknockbackend/global/error/exception/ErrorCode.java
  src/main/resources/application.yml
  src/main/resources/data.sql
Labels: 기능 추가, 리팩토링

#64 🔀 :: (#49) 도커파일 세팅
  .gitignore
  Dockerfile
Labels: 프로젝트 설정

#66 🔀 :: (#65) baseTimeEntity 추가
  src/main/java/io/github/depromeet/knockknockbackend/KnockKnockBackendApplication.java
  src/main/java/io/github/depromeet/knockknockbackend/global/config/JpaAuditingConfig.java
  src/main/java/io/github/depromeet/knockknockbackend/global/database/BaseTimeEntity.java
Labels: 기능 추가, 프로젝트 설정

#63 🔀 :: (#38) 방장 그룹 관련 설정 , 제거
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/domain/Group.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/domain/GroupUsers.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/exception/GroupNotFoundException.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/exception/NotHostException.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/presentation/GroupController.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/presentation/dto/request/UpdateGroupRequest.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/presentation/dto/response/GroupResponse.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/service/GroupService.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/service/dto/UpdateGroupDto.java
  src/main/java/io/github/depromeet/knockknockbackend/global/error/exception/ErrorCode.java
Labels: 기능 추가

#67 🔀 :: (#34)UserUtilsImpl
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/service/GroupService.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/relation/domain/repository/RelationRepository.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/relation/service/RelationService.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/user/UserRelationService.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/user/presentation/dto/response/QueryUserByNicknameResponseElement.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/user/service/UserService.java
  src/main/java/io/github/depromeet/knockknockbackend/global/utils/user/UserUtils.java
  src/main/java/io/github/depromeet/knockknockbackend/global/utils/user/UserUtilsImpl.java
Labels: 기능 추가

#70 🔀 :: (#60) QueryDSL 설정
  build.gradle
  src/main/java/io/github/depromeet/knockknockbackend/global/config/QuerydslConfig.java
Labels: 프로젝트 설정

#68 🔀 :: (#40)카테고리 조회 , 추가
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/domain/repository/CategoryRepository.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/presentation/GroupController.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/presentation/dto/request/CreateCategoryRequest.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/presentation/dto/response/CategoryDto.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/presentation/dto/response/CategoryListResponse.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/service/CategoryService.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/service/GroupService.java
Labels: 기능 추가

#69 🔀 :: (#54) 그룹 탐색탭 관련
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/domain/Category.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/domain/Group.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/domain/GroupUser.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/domain/GroupUsers.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/domain/repository/GroupRepository.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/domain/repository/GroupUserRepository.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/domain/repository/MemberRepository.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/presentation/GroupController.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/presentation/dto/request/GroupInTypeRequest.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/presentation/dto/response/GroupBriefInfoDto.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/presentation/dto/response/GroupBriefInfoListResponse.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/service/CategoryService.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/group/service/GroupService.java
  src/main/java/io/github/depromeet/knockknockbackend/global/utils/user/UserUtils.java
  src/main/java/io/github/depromeet/knockknockbackend/global/utils/user/UserUtilsImpl.java
Labels: 기능 추가
