Repository depromeet/KnockKnock-Backend, pull requests merged in 2023-01, with the labels that each got.

#270 🔀 :: (#269) 닉네임으로 검색 Api 버그
  src/main/java/io/github/depromeet/knockknockbackend/domain/user/domain/repository/UserRepository.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/user/service/UserService.java
Labels: 버그

#274 🔀 :: (#268) 토큰 없을 경우 notification 히스토리는 남도록 수정
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/service/NotificationService.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/service/NotificationUtils.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/service/NotificationUtilsImpl.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/service/ReservationService.java
Labels: 리팩토링

#275 🔀 :: (#256) 메인 알림 친구 관련 이벤트 생성
  src/main/java/io/github/depromeet/knockknockbackend/domain/alarm/domain/Alarm.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/alarm/service/AlarmService.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/alarm/service/CreateAlarmService.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/alarm/service/dto/CreateAlarmDto.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/relation/service/RelationService.java
Labels: 기능 추가

#278 🔀 :: (#277) 알림 목록에 리액션 이미지 url 정보 추가 #277
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/domain/vo/NotificationReactionCountInfoVo.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/reaction/domain/repository/NotificationReactionRepository.java
Labels: 기능 추가

#279 🚀 :: v0.1.7-2
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/domain/vo/NotificationReactionCountInfoVo.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/reaction/domain/repository/NotificationReactionRepository.java
Labels: 기능 추가

#281 🔀 :: (#280) API 요청값 validation 처리
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/presentation/NotificationController.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/presentation/dto/request/ChangeSendAtReservationRequest.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/presentation/dto/request/RegisterFcmTokenRequest.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/presentation/dto/request/SendInstanceRequest.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/presentation/dto/request/SendInstanceToMeBeforeSignUpRequest.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/presentation/dto/request/SendReservationRequest.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/reaction/presentation/ReactionController.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/reaction/presentation/dto/request/RegisterReactionRequest.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/storage/presentation/StorageController.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/storage/presentation/dto/request/DeleteStorage.java
Labels: 리팩토링

#286 🔀 :: (#285) Error Response Status
  src/main/java/io/github/depromeet/knockknockbackend/domain/relation/domain/repository/CustomRelationRepositoryImpl.java
  src/main/java/io/github/depromeet/knockknockbackend/global/error/ExceptionFilter.java
Labels: chore

#284 🔀 :: (#283) 친구 추가 버그
  src/main/java/io/github/depromeet/knockknockbackend/domain/relation/domain/repository/CustomRelationRepositoryImpl.java
Labels: 버그

#290 🔀 :: (#282) FCM 메세지 전송 로그 처리
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/exception/FcmServerException.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/exception/FcmTokenInvalidException.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/exception/NotificationInvalidFcmToken.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/service/NotificationService.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/service/NotificationUtils.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/notification/service/NotificationUtilsImpl.java
  src/main/java/io/github/depromeet/knockknockbackend/global/error/exception/ErrorCode.java
  src/main/java/io/github/depromeet/knockknockbackend/infrastructor/fcm/FcmService.java
Labels: 리팩토링

#291 🔀 :: (#288) 리액션 익셉션 처리
  src/main/java/io/github/depromeet/knockknockbackend/domain/reaction/domain/NotificationReaction.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/reaction/exception/ReactionNotExistException.java
  src/main/java/io/github/depromeet/knockknockbackend/domain/reaction/service/ReactionService.java
  src/main/java/io/github/depromeet/knockknockbackend/global/error/exception/ErrorCode.java
Labels: 리팩토링

#293 🔀 :: (#292) Relation Entity버그
  src/main/java/io/github/depromeet/knockknockbackend/domain/relation/domain/Relation.java
Labels: 버그
